twig:
    default_path: '%kernel.project_dir%/templates/Britania'
    globals:
        theme: 'Britania'
        settings: '@App\Settings\CmsSettings'
        tinymce_key: '%tinymce.key%'
        max_level: '%max_level%'
