twig:
    default_path: '%kernel.project_dir%/templates/'
    paths: 
        '%kernel.project_dir%/src/Controller/Plugins/': Plugins
    globals:
        settings: '@App\Settings\CmsSettings'
        api: '@App\Settings\Api'