twig:
    paths:
        '%kernel.project_dir%/templates/': 'default_path'
        '%kernel.project_dir%/src/Plugins/': 'plugins'
        '%kernel.project_dir%/templates/AdminPanel': 'AdminPanel'
    globals:
        settings: '@App\Settings\CmsSettings'
        api: '@App\Settings\Api'
        checkPlugin: '@App\Services\CheckPlugins'
        paymentManager: '@App\Managers\PaymentManager'