controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: '{_locale}'
    requirements:
        _locale: en|fr|es
kernel:
    resource: ../../src/Kernel.php
    type: annotation
